# vim:tabstop=4:shiftwidth=4:expandtab
services:
    app:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: pnpm dev
