# vim:tabstop=4:shiftwidth=4:expandtab
services:
    app:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        command: pnpm dev
        depends_on:
            - mongo
            - redis
    mongo:
        image: mongo:7
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
    redis:
        image: redis:7
        ports:
            - "6379:6379"

volumes:
    mongo-data:
