# vim:tabstop=4:shiftwidth=4:expandtab
services:
    paz:
        image: felixkyun/paz:latest
        ports:
            - "3000:3000"
        depends_on:
            - mongo
            - redis
        env_file:
            - .env
    mongo:
        image: mongo:7
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
    redis:
        image: redis:7
        ports:
            - "6379:6379"

volumes:
    mongo-data:
